#!/bin/bash

#SBATCH --ntasks=1
#SBATCH -t 180:00:00      # Max runtime is 180 hours (9 days)
#SBATCH -J iqn_cql_opt       # name
#SBATCH --mem=64GB
#SBATCH -c 4              # Number of cpus
#SBATCH --gres=gpu:1      # Requesting a GPU
#SBATCH -p ml4h
#SBATCH -A ml4h
#SBATCH --qos=ml4h
#SBATCH -o OUTPUTS/iqn_cql_opt_%J.log

date;hostname;pwd

source /ais/bulbasaur/twkillian/envs/uncded_env

export XDG_RUNTIME_DIR=""

python finetune_rl.py --config rl_finetuning_config