seed: 2022
num_actions: 25
num_q_hidden_units: 64
num_q_layers: 2
gamma: 1.0
lr: 0.00025
tau: 0.005
num_iqn_samples_train: 32
num_iqn_samples_est: 32
drm: "identity"
dueling: False
noisy_layer: False
q_update_freq: 5
data_dir: "data/continuous_mimic/rectilinear_processed/"
train_batch_size: 64
val_batch_size: 128
num_ps: 0
num_ns: 2
use_cql: False
model: "IQN"
num_epochs: 100
saving_period: 1
checkpoint_fname: "runs/iqn_discrete_mimic/"
