## TODO Document this... Make it look similar to https://github.com/microsoft/med-deadend/blob/main/config_sepsis.yaml

## The following configuration parameters are for hyperparameter optimization of the Online NCDE state aggregator
data_dir: "/ais/bulbasaur/twkillian/AHE_Sepsis_Data/rectilinear_processed/"
output_dir: "/ais/bulbasaur/twkillian/UncDeD_Results/NCDE/"
total_trials: 50
seed: 2022
batch_size: 128
parameterization: [
        {"name": "hidden_dim", "type": "range", "bounds": [32, 128]},
        {"name": "hidden_hidden_dim", "type": "range", "bounds": [32, 128]},
        {"name": "pred_num_layers", "type": "range", "bounds": [1, 4]},
        {"name": "pred_num_units", "type": "range", "bounds": [32, 128]},
        # {"name": "lr", "type": "range", "bounds": [0.00001, 0.001], "log_scale": True},
        {"name": "lr", "type": "fixed", "value": 0.0005},
        {"name": "lr_step_size", "type": "range", "bounds": [10, 30]},
        {"name": "lr_gamma", "type": "choice", "values": [0.1, 0.5, 0.9, 1.0], "is_ordered": True},
        {"name": "num_training_epochs", "type": "choice", "values": [10, 25, 50]},]